version: '3.4'

services:
  creativetim.argon.dotnetcore.free:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44308
      - CONNECTIONSTRINGS__POSTGRESCONNECTION=host=db;database=creativeTim;user id=creativeTim;password=creativeTim
      - REDIS__INSTANCENAME=redis
    ports:
      - "60151:80"
      - "44308:443"
    volumes:
      # Use this share instead for the computer-global development HTTPS certificates
      # - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      #
      # Or this for the user-specific development HTTPS certificates
      - ${USERPROFILE}/.aspnet/https:/root/.aspnet/https/
      # Use this to share the application secrets within the Docker image
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
