version: '3.4'

services:
  db:
    # We need to do this to get the PostgreSQL container to work on Windows
    build:
      context: .
      dockerfile: Dockerfile.postgresql-container
    environment:
      PGDATA: '/var/lib/postgresql/data'
      POSTGRES_USER: 'creativeTim'
      POSTGRES_PASSWORD: 'creativeTim'
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379

volumes:
  pgdata:
    driver: local